# Generated by Django 5.2.8 on 2025-12-04 20:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('barista', 'Barista'), ('mesero', 'Mesero'), ('gerente', 'Gerente'), ('cocinero', 'Cocinero'), ('otro', 'Otro')], max_length=20)),
                ('pago_por_hora', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.empleado')),
            ],
            options={
                'ordering': ['fecha', 'dia_semana', 'hora_inicio'],
                'unique_together': {('empleado', 'fecha', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, default=None, null=True)),
                ('hora_salida', models.TimeField(blank=True, default=None, null=True)),
                ('estado', models.CharField(choices=[('asistió', 'Asistió'), ('no_asistió', 'No Asistió'), ('justificado', 'Justificado')], default='no_asistió', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.empleado')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.horario')),
            ],
            options={
                'ordering': ['-fecha', 'empleado'],
                'unique_together': {('empleado', 'horario', 'fecha')},
            },
        ),
    ]
