# Generated by Django 5.2.8 on 2025-12-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_asistencia_hora_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_desactivacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
