# Generated by Django 5.2.8 on 2025-12-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_insumo_producto_productoreceta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='codigo_barra',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidad')], max_length=10),
        ),
    ]
