# Generated by Django 5.2.8 on 2025-12-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_insumo_codigo_barra_alter_insumo_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoreceta',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidad'), ('docena', 'Docena')], default='unidad', max_length=10),
        ),
    ]
