# Generated by Django 5.2.8 on 2025-12-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productoreceta_unidad'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('empleado', 'fecha')},
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='horario',
        ),
    ]
