# Generated by Django 5.2.8 on 2025-12-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_asistencia_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='estado',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
