# Generated by Django 5.2.8 on 2025-12-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_asistencia_estado_asistencia_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(blank=True, help_text='Hash de la contraseña', max_length=128),
        ),
    ]
