# Generated by Django 5.2.8 on 2025-12-07 01:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Identificador único para la venta (ej: Orden #1)', max_length=100)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(help_text='Nombre del producto (editable por personalización)', max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProductoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidad'), ('docena', 'Docena')], default='unidad', max_length=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.insumo')),
                ('venta_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_personalizada', to='core.ventaproducto')),
            ],
        ),
    ]
