# Generated by Django 5.2.8 on 2025-12-07 02:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_venta_ventaproducto_ventaproductoreceta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaproductoreceta',
            name='venta_producto',
        ),
        migrations.RemoveField(
            model_name='ventaproductoreceta',
            name='insumo',
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='costo_total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='precio_total',
        ),
        migrations.AddField(
            model_name='venta',
            name='costo_total_cache',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_total_cache',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='puntos_usados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaItemReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml'), ('unidad', 'unidad'), ('docena', 'docena')], default='unidad', max_length=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.insumo')),
                ('venta_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_items', to='core.ventaitem')),
            ],
        ),
        migrations.DeleteModel(
            name='VentaProducto',
        ),
        migrations.DeleteModel(
            name='VentaProductoReceta',
        ),
    ]
