# Generated by Django 5.2.8 on 2025-12-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ventaitem_options_alter_venta_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
    ]
