# Generated by Django 5.2.8 on 2025-12-07 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_venta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaitem',
            name='nombre',
        ),
        migrations.DeleteModel(
            name='VentaItemReceta',
        ),
    ]
